### ISSUE TITLE
Document all modules

### ISSUE THREAD

**Issue by kaneda** [myano/jenni#142]
Document all modules, including defaults

**Comment by myano** [comment]
:+1:

**Comment by A-C-Smith** [comment]
@kaneda If you would like any help with documentation, I'd be happy to help. That is, if you aren't nearly done.

As a major developer on this project, you could (and should) focus on other issues. 

However, I have never formally documented anything before and would need to be given a specification for the general standard of documentation. How you would like it formatted, how precise you would like it, etc.

**Comment by kaneda** [comment]
@A-C-Smith sure, can you take a look at the wiki and see if anything's missing? Likewise it would be great if we had better documentation on not only the commands but the APIs and/or endpoints behind them, in order to ascertain maintenance cost for breaking changes.

**Comment by A-C-Smith** [comment]
@kaneda Looking through the wiki, I couldn't find anything that wasn't well documented. It looks like you've done a very good job in the few days the issue has been open.

**Comment by kaneda** [comment]
@A-C-Smith feel free to close out the issue if you feel it's been resolved

**Comment by myano** [comment]
Hm.

I'm all for having help available on GitHub's wiki page for people who don't want to have to install or talk to jenni. This is already in place. One of the things I had removed, mostly because it was severely broken, was the command lookup on-IRC. An IRC "help" might be useful, but I feel can be pretty spammy in an attempt to just convey a basic description *and* an example. Also the other thing that should be fixed, assuming we bring this feature back: is the ability to not have every single function in jenni being assumed it is a command. This was a problem when .help was working, all functions were being advertised as possible commands with the .commands, as I think originally function names use to be the same as the actual commands.

Thoughts?

**Comment by kaneda** [comment]
@myano I don't like the idea of maintaining the list in two places, that's my only concern. I'm happy to bring back help with the ACTUAL commands in place but we'd need to implement a good process to ensure that the docs get updated.

Today when a new command is added, as soon as it's merged down (or merge is inevitable) I've been trying to update the wiki (so far so good). We could then put the onus on the developer to ensure that their command is available from the help function jenni as well.

**Comment by A-C-Smith** [comment]
To keep help from becoming *too* spammy, would it be possible to consider some modules more "important" or "interesting" than others, and by default only return help for them? 

For example, the weather module and calc modules are used far more often than the units and youtube modules. This should be easy to change so that anyone using jenni can pick and choose what is "important."

With the addition of a ".help all" ability, this seems like a good way to keep it reasonable.

**Comment by kaneda** [comment]
@A-C-Smith sure, though I'd be looking for recommendations about what are important or better-used modules and functions therein.

**Comment by A-C-Smith** [comment]
@kaneda That is a hard thing to outline. Like I mentioned, there could be a default list (possibly based on frequency of use) along with making it simple enough to be changed.

**Comment by kaneda** [comment]
@A-C-Smith check out https://github.com/myano/jenni/pull/146 for the commands I've added to the common commands list. If you have any others you'd like to add feel free to tack on.
