### ISSUE TITLE
YouTube module broken

### ISSUE THREAD

**Issue by n0ided** [myano/jenni#170]
The yt module is broken, redirects to http://youtube-eng.blogspot.se/2014/03/committing-to-youtube-data-api-v3_4.html

**Comment by myano** [comment]
Well, it is sort of broken. The auto-title part seems to still work, as of
a couple days ago, but the other manual youtube stuff, like the search
seems to have broken.

**Comment by n0ided** [comment]
@myano The translate module is broken as well.

**Comment by kaneda** [comment]
@myano assigned to myself, feel free to snag it if you want it instead

**Comment by kaneda** [comment]
Addressed by https://github.com/myano/jenni/pull/173

**Comment by myano** [comment]
@n0ided Google Translate isn't going to be fixed. Google intentionally broke it and is now charging money for translations.

https://cloud.google.com/translate/v2/pricing

**Comment by myano** [comment]
Also, I have removed youtube.py because, Google sucks and has decided to break everything. So unless somebody really wants to build a *new* YouTube module that uses the lateast API, go right ahead. I don't care enough anymore for Google Services to even bother with trying to keep up with their shit.
